create table ZOO.ANIMALS (
    animal_id integer generated by default as identity,
    kind varchar(64),
    name varchar(64),
    hunter varchar(64),
    primary key (animal_id)
)

GO

insert into ZOO.ANIMALS (
    name, kind, hunter)
    values('обезьяна', 'млекопитающее', 'нет'
)

GO

insert into ZOO.ANIMALS (
    name, kind, hunter)
    values('заяц', 'млекопитающее', 'нет'
)

GO

insert into ZOO.ANIMALS (
    name, kind, hunter)
    values('орёл', 'птица', 'да'
)

GO

insert into ZOO.ANIMALS (
    name, kind, hunter)
    values('тигр', 'млекопитающее', 'да'
)

GO

insert into ZOO.ANIMALS (
    name, kind, hunter)
    values('лошадь', 'млекопитающее', 'нет'
)