create table ZOO.PRODUCTS (
    product_id integer generated by default as identity,
    name varchar(64),
    quantity bigint,
    type varchar(64),
    unit varchar(64),
    primary key (product_id)
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('морковь', 100, 'шт', 'овощ'
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('мясо', 10, 'кг', 'мясо'
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('капуста', 50, 'шт', 'овощ'
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('банан', 65, 'шт', 'фрукт'
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('яблоко', 0, 'шт', 'фрукт'
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('зерно', 1000, 'кг', 'овощ'
)

GO

insert into ZOO.PRODUCTS (
    name, quantity, unit, type)
    values('вода', 500, 'л', 'жидкость'
)