create table ZOO.FOOD_RATES (
    id integer generated by default as identity,
    rate bigint,
    unit varchar(64),
    animal_id integer,
    product_id integer,
    primary key (id)
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(1, 7, 10, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(1, 4, 8, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(1, 5, 5, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(2, 1, 10, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(2, 3, 4, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(2, 7, 8, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(3, 7, 12, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(3, 2, 5, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(3, 6, 15, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(3, 5, 4, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(4, 2, 50, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(4, 7, 60, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(5, 7, 80, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(5, 6, 100, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(5, 5, 30, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product_id, rate, unit)
    values(5, 1, 20, 'шт'
)