create table ZOO.FOOD_RATES (
    id integer generated by default as identity,
    product varchar(64),
    rate bigint,
    unit varchar(64),
    animal_id integer,
    primary key (id)
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(1, 'вода', 10, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(1, 'банан', 8, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(1, 'яблоко', 5, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(2, 'морковь', 10, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(2, 'капуста', 4, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(2, 'вода', 8, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(3, 'вода', 12, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(3, 'мясо', 5, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(3, 'зерно', 15, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(3, 'яблоко', 4, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(4, 'мясо', 50, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(4, 'вода', 60, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(5, 'вода', 80, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(5, 'зерно', 100, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(5, 'яблоко', 30, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal_id, product, rate, unit)
    values(5, 'морковь', 20, 'шт'
)