create table ZOO.FOOD_RATES (
    id integer generated by default as identity,
    animal varchar(64),
    product varchar(64),
    rate bigint,
    unit varchar(64),
    primary key (id)
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('обезьяна', 'вода', 10, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('обезьяна', 'банан', 8, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('обезьяна', 'яблоко', 5, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('заяц', 'морковь', 10, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('заяц', 'капуста', 4, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('заяц', 'вода', 8, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('орёл', 'вода', 12, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('орёл', 'мясо', 5, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('орёл', 'зерно', 15, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('орёл', 'яблоко', 4, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('тигр', 'мясо', 50, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('тигр', 'вода', 60, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('лошадь', 'вода', 80, 'л'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('лошадь', 'зерно', 100, 'кг'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('лошадь', 'яблоко', 30, 'шт'
)

GO

insert into ZOO.FOOD_RATES (
    animal, product, rate, unit)
    values('лошадь', 'морковь', 20, 'шт'
)